gitlab-server:
  ports:
  - "${gitlab_public_ip}:${ssh_port}:22"
  - "${gitlab_public_ip}:80:80"
  - "${gitlab_public_ip}:443:443"
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:8.5.1-ce.0
  volumes_from:
  - gitlab-data
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://${gitlab_hostname}'
      gitlab_rails['gitlab_shell_ssh_port'] = ${ssh_port}

gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: gitdata
  image: gitlab/gitlab-ce:8.5.1-ce.0
  volumes:
  - /etc/gitlab
  - /var/log/gitlab
  - /var/opt/gitlab

