.catalog:
  name: Gitlab Community
  version: 8.5.1-0
  description: |
    Gitlab CE is a free GitHub alternative
  minimum_rancher_version: v0.56.0
  maintainer: "Alexis Ducastel <alexis@ducastel.net>"
  uuid: qrg-gitlab-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname"
      label: "Hostname:"
      required: true
      default: "git.example.com"
      type: "string"
    - variable: "gitlab_public_ip"
      description: "GitLab Public IP"
      label: "IP Address:"
      required: true
      type: "string"
      default: "0.0.0.0"
    - variable: "ssh_port"
      description: "SSH Port"
      label: "Port:"
      required: false
      type: int
      default: 2222

gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

gitlab-data:
  scale: 1
  retain_ip: true

